### ISSUE TITLE
Thanks for your  code谢谢你的代码

### ISSUE THREAD

**Issue by yan1990y** [vencewill/Wormhole#2]
你好，我看过example了，由于我是初学者，还有些看不明白，能不能出个简单教程？非常感谢！
Hello ，I had learned your example,But I am a starter,Can you write some simple demo?Thanks a lot!

**Comment by mengoreo** [comment]
哈哈，我也是国人。其实写完这个，然后打算发布 pod 的时候发现已经有人写过 Swift 的版本了。[这位作者](https://github.com/nixzhu/Wormhole)还附带了中文教程，虽然没点进去看。但应该也会给你带来帮助哈。

> Demo 是用 SwiftUI 写的，设计模式也没用常见的 MVVM 组织。而是简单用了下  [Elm](https://guide.elm-lang.org/architecture/) 里注入的概念，也顺便加深我对其的理解。所以对初学者来讲可能有点难看懂。
