### ISSUE TITLE
Registered notifications are not get called. 

### ISSUE THREAD

**Issue by Meonardo** [vencewill/Wormhole#3]
Environment: 
**Xcode 12.5, iOS 14.4.**
Container App: 
`wormhole.listenForMessage(with: someID, listener: Closure)`
Extensions:
`wormhole.passMessage(data, with: someID)`
`Closue` never get called.

--------------------------

There is an issue in 
File: `Wormhole.swift`: `NotificationCenter.default.addObserver(self, selector: #selector(didRecieveNotification(_:)), name: .wormhole, object: self)`
or
File: `Helpers.swift` `NotificationCenter.default.post(name: .wormhole, object: nil, userInfo: ["identifier": identifier])`
have to pass the same object in `object` field or just pass `nil` to `addObserver... object: nil`.

**Comment by mengoreo** [comment]
Sorry for the late reply and the inconvenience. 🙏🏻

This repo is a duplicated work of [nixzhu](https://github.com/nixzhu/Wormhole) which is better documented. So I don't think I will maintain it in the future.
